excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
line_length: 150
cyclomatic_complexity: 14
function_body_length: 90
identifier_name:
 excluded: 
  - id
  - a
  - b
  - c
  - f
type_name:
 excluded:
  - Di
large_tuple: 3

