# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


lane :test do
    # add actions here: https://docs.fastlane.tools/actions
end

lane :deploy do

	# ensure_git_status_clean

	# clear data
	# clear_derived_data
	# xcclean(
	#	scheme: "GBShop",
	#	workspace: "GBShop.xcworkspace"
	#)

	# update dependencies
	#cocoapods(
	#	use_bundle_exec: false
	#)

	# run tests
	# run_tests

	# make screenshots
    # capture_ios_screenshots

    #increment_build_number

    #set_info_plist_value(path: "./GBShop/Environments/Info.plist", key: "CFBundleShortVersionString", value: "2.0")

    # gym(
    #	scheme: "GBShop",
    #	configuration: "Debug",
    #	export_method: "development",
    #	include_symbols: true,
    #	include_bitcode: true,
    #	silent: false
    #	)

    # commit changes to git
    # versionNumber = get_version_number
    # buildNumber = get_build_number
    # tag = "#{versionNumber}.#{buildNumber}"

    # git add
    # git_add(path: ["./Podfile.lock", "./GBShop.xcodeproj/project.pbxproj", "./GBShop/Environments/Info.plist"])
    # git_commit(path: ["./Podfile.lock", "./GBShop.xcodeproj/project.pbxproj", "./GBShop/Environments/Info.plist"], message: "version up")
    # add_git_tag(
    #	tag: tag
    # )

end